import type { Metadata } from "next";
import "./globals.css";
import NavbarWrapper from "./components/NavbarWrapper";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
        />
      </head>

      <body className="antialiased h-screen ">
        <NavbarWrapper />   {/* stays fixed at top */}
        
        {/* Push content below navbar height */}
        <main className="pt-[70px] h-full overflow-auto custom-scroll">
          {children}
        </main>
      </body>
    </html>
  );
}
